<?php
$LOWCAL_CONFIG_ARRAY['OUTPUT_COMPRESSION'] = false;
$LOWCAL_CONFIG_ARRAY['OUTPUT_BUFFERING'] = false;

$LOWCAL_CONFIG_ARRAY['DOMAIN_PROTECTION'] = false;
$LOWCAL_CONFIG_ARRAY['DOMAIN_ALLOWED_DOMAINS'] = '';
$LOWCAL_CONFIG_ARRAY['DOMAIN_SOLUTION'] = array('type' => '', 'value' => '');